import type { Level,Activity } from './types';
const data:[string,string,string,string,[string,string,string][]][]=[
 ['Guitar Explorer','Your first steps into a world of music.','guitar-explorer','Hold your guitar comfortably and make your first controlled sounds.',[['guitar-parts','Guitar parts','Find the body, neck, headstock, tuning pegs, frets, fretboard, nut, bridge and sound hole.'],['string-numbers','String numbers','String 1 is the thinnest, high E. String 6 is the thickest, low E.'],['finger-numbers','Finger numbers','Index 1, middle 2, ring 3, pinky 4. Your thumb is not numbered.'],['holding','Holding your guitar','Sit comfortably, keep shoulders relaxed, and support the guitar without gripping the neck.'],['picking','Your first notes','Hold the pick lightly and play several controlled notes.']]],
 ['First Notes','Small movements. Clear, confident notes.','fretboard-rookie','Play three clean notes in a row with deliberate finger placement.',[['fretting','Clean fretting','Press just behind the fret, not on top of it.'],['note-pattern','First note pattern','Play frets 0–1–2–3 slowly on strings 1 and 2.']]],
 ['First Chords','A few fingers. A whole new sound.','chord-builder','Build Em and Am from memory, three times each.',[['chord-em','E minor (Em)','Place fingers 2 and 3 on strings 5 and 4 at fret 2. Strum all six strings.'],['chord-am','A minor (Am)','Finger 1: string 2, fret 1. Finger 2: string 4, fret 2. Finger 3: string 3, fret 2. Strum strings 5–1.']]],
 ['Rhythm & Strumming','Find the steady beat inside every song.','rhythm-keeper','Keep a relaxed, steady pattern for about 30 seconds.',[['pulse','Steady pulse','Count 1–2–3–4 with slow downstrokes.'],['strumming','Down and up','Try D U D U, counting 1 & 2 &.']]],
 ['Chord Changes','Bring your favorite shapes together.','chord-switcher','Remember both chord shapes and move between them with a steady rhythm.',[['changes','Em to Am','Change slowly between Em and Am. Clean movement matters more than speed.']]],
 ['My First Song','Turn your practice into music.','first-song','Play a teacher-selected progression with recognizable chords and continuous rhythm.',[['first-song','Your first progression','Your teacher selects a song using chords you know. Practice one section at a time.']]],
 ['Guitar Player','Make music with growing confidence.','guitar-player','Read a chord chart and play three songs or substantial progressions.',[['charts','Reading chord charts','Follow chord names and section changes independently.'],['repertoire','Build your repertoire','Prepare three familiar songs or substantial progressions.']]],
 ['Independent Musician','Learn how to learn your next song.','independent-musician','Prepare a familiar-style progression with limited guidance.',[['independence','Independent preparation','Identify chords, choose a slow tempo, and troubleshoot one small section at a time.']]]
];
export const levels:Level[]=data.map(([title,description,badgeId,goal,skills],i)=>({id:`level-${i+1}`,order:i+1,title,description,badgeId,goal,skills:skills.map(([id,title,description])=>({id,title,description,required:true,levelId:`level-${i+1}`}))}));
export const skills=levels.flatMap(l=>l.skills);
export const activities:Activity[]=[
 {id:'parts',skillId:'guitar-parts',title:'Meet your guitar',description:'Get to know the parts that make the music.',minutes:2,kind:'parts',steps:['Find the body: the large part resting against you.','Follow the neck to the headstock and tuning pegs.','Find the bridge where the strings attach to the body.']},
 {id:'strings',skillId:'string-numbers',title:'String explorer',description:'Find your way around all six strings.',minutes:2,kind:'strings',steps:['Look down at your guitar in playing position.','String 1 is the thinnest. String 6 is the thickest.','Pick strings 1, 2, then 6 gently.']},
 {id:'fingers',skillId:'finger-numbers',title:'Give your fingers a number',description:'Four fingers, four helpful numbers.',minutes:2,kind:'fingers',steps:['Wiggle your index finger: number 1.','Middle is 2, ring is 3, pinky is 4.','Keep your thumb relaxed behind the neck.']},
 {id:'holding',skillId:'holding',title:'Get comfortable',description:'Relax your shoulders and settle in.',minutes:2,kind:'notes',steps:['Sit upright with both feet supported.','Rest the guitar securely against your body.','Let your shoulders soften. Stop and tell your teacher if anything hurts.']},
 {id:'first-notes',skillId:'picking',title:'Your first little melody',description:'Make music on just one string.',minutes:3,kind:'notes',steps:['Pick the open thinnest string twice: 0 — 0.','Press near fret 1 with finger 1, then pick: 1 — 1.','Release and finish on the open string: 0. Go slowly and enjoy the sound.']},
 {id:'em-shape',skillId:'chord-em',title:'Hello, E minor',description:'Warm up with a chord you know.',minutes:3,kind:'chord',chordId:'Em',steps:['Place fingers 2 and 3 at fret 2 on strings 5 and 4.','Pick each string slowly. Curve your fingers to let the others ring.','Strum all six strings. Relax, lift your hand, and try again.']},
 {id:'am-shape',skillId:'chord-am',title:'Make friends with A minor',description:'Take your time. Let each string ring.',minutes:5,kind:'chord',chordId:'Am',steps:['Finger 1 goes on string 2, fret 1.','Fingers 2 and 3 go on strings 4 and 3, fret 2.','Strum from string 5. Keep the thickest string quiet.']},
 {id:'am-reconstruction',skillId:'chord-am',title:'Rebuild Am from memory',description:'A little memory practice for your fingers.',minutes:3,kind:'builder',chordId:'Am',steps:['Look closely at the chord shape.','Hide the guide and place the three fingers in the diagram.','On your guitar, rebuild the shape slowly three times.']},
 {id:'am-placement',skillId:'chord-am',title:'One finger at a time',description:'Build a relaxed, accurate shape.',minutes:3,kind:'chord',chordId:'Am',steps:['Place just finger 1 on string 2, fret 1.','Add fingers 2 and 3 slowly.','Release extra pressure and rebuild without rushing.']},
 {id:'am-tone',skillId:'chord-am',title:'Let every string sing',description:'Listen for a clear note, one string at a time.',minutes:3,kind:'chord',chordId:'Am',steps:['Build Am and pick strings 5 through 1 separately.','For a muted string, check whether another finger touches it.','Move fingertips near the fret and use only enough pressure to sound the note.']},
 {id:'rhythm',skillId:'pulse',title:'Find your steady beat',description:'Four easy downstrokes. One steady pulse.',minutes:2,kind:'rhythm',steps:['Set a comfortable tempo between 40 and 80 BPM.','Count 1–2–3–4 with the pulse.','Strum D D D D. If you lose the beat, breathe and rejoin.']},
 {id:'transitions',skillId:'changes',title:'A little chord conversation',description:'Move slowly between Em and Am.',minutes:3,kind:'transition',chordId:'Am',steps:['Build Em and strum once.','Move to Am with relaxed fingers.','Repeat slowly. Pause to find a clean shape whenever you need.']}
];
export const activityById=(id:string)=>activities.find(a=>a.id===id);
export const reinforcement={placement:'am-placement',memory:'am-reconstruction','clean-tone':'am-tone',rhythm:'rhythm',transition:'transitions',other:'am-placement'} as const;
