import {useEffect,useRef,useState} from 'react';
import {Volume2} from 'lucide-react';
export function Metronome(){const [bpm,setBpm]=useState(60),[running,setRunning]=useState(false),[beat,setBeat]=useState(0),[warning,setWarning]=useState(''),[countIn,setCountIn]=useState(false);const audio=useRef<AudioContext|null>(null),count=useRef(0);
 useEffect(()=>{if(!running)return;let next=(audio.current?.currentTime??performance.now()/1000)+.08;let visual=performance.now()+80;let tick=0;count.current=0;const pending=new Set<ReturnType<typeof setTimeout>>();
 const interval=setInterval(()=>{const ctx=audio.current;const now=ctx?.currentTime??performance.now()/1000;while(next<now+.12){const n=tick++;if(ctx){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=n%4===0?1000:700;gain.gain.setValueAtTime(.12,next);gain.gain.exponentialRampToValueAtTime(.001,next+.06);osc.start(next);osc.stop(next+.07);}const delay=Math.max(0,visual-performance.now());const timer=setTimeout(()=>{setBeat(n%4);count.current=n+1;pending.delete(timer);},delay);pending.add(timer);next+=60/bpm;visual+=60000/bpm;}},25);
 const hidden=()=>{if(document.hidden)setRunning(false);};document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(interval);pending.forEach(clearTimeout);document.removeEventListener('visibilitychange',hidden);void audio.current?.suspend();};},[running,bpm]);
 useEffect(()=>()=>{void audio.current?.close();},[]);
 async function toggle(){if(running){setRunning(false);return;}try{audio.current??=new AudioContext();await audio.current.resume();setWarning('');}catch{audio.current=null;setWarning('Audio is unavailable. Follow the visual pulse.');}setRunning(true);}
 return <section className="metronome"><div className="row spread"><h3><Volume2 size={17}/> Your steady beat</h3><span className="small">{countIn&&running&&count.current<4?'Count in…':'4 beats'}</span></div><div className="beat-dots" aria-label={running?`Beat ${beat+1}`:'Metronome stopped'}>{[0,1,2,3].map(n=><span className={running&&beat===n?'pulse active':'pulse'} key={n}>{n+1}</span>)}</div><div className="row spread"><label>BPM <input aria-label="Beats per minute" type="number" min="40" max="80" value={bpm} onChange={e=>{setRunning(false);setBpm(Math.max(40,Math.min(80,Number(e.target.value)||40)));}}/></label><button className="button secondary" onClick={()=>void toggle()}>{running?'Stop beat':'Start beat'}</button></div><label className="check-label"><input type="checkbox" checked={countIn} onChange={e=>setCountIn(e.target.checked)}/> Four-beat count-in cue</label>{warning&&<p role="status">{warning}</p>}</section>;
}
